//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHARPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNota
    {
        public int idNota { get; set; }
        public int idBarang { get; set; }
        public int idCustomer { get; set; }
        public System.DateTime tglMasuk { get; set; }
        public Nullable<System.DateTime> tglDiambil { get; set; }
        public int idStatus { get; set; }
    }
}
